### ISSUE TITLE
Location API Service

### ISSUE THREAD

**Issue by wfischer42** [make4covid/aerosolve#16]
Create a service that connects to the CDC data sources for vaccination rates and infection rates.

I'm thinking the service will be run from the Location Page whenever the location is updated, and the results will update state. A simple promise wrapper should do the trick. It could also be implemented in a custom hook so component based consumption is super easy, but that's not entirely necessary.

Example Usage:
```js
const localCovidData = await api.getLocalCovidData({state: "Colorado"})
```

**Comment by nnbaokhang** [comment]
Done with implementation. Need to verify
