### ISSUE TITLE
`SelectionPercentages` component

### ISSUE THREAD

**Issue by wfischer42** [make4covid/aerosolve#29]
For "Advanced" options on a couple step pages.

- Includes a set of selection rows
- Percentage sum should always equal 100%
- Increasing one should decrease another
- can lock or unlock rows

This is more difficult to implement than some of the others, and lower priority, since we can start with basic-only on those pages.

**Comment by nnbaokhang** [comment]
I kind of understand this task so I guess I can pull this into my work.
